Amsterdam/Vergunningschecker

- app/components/Questionnaire/Answers.js
- app/containers/QuestionnaireContainer/index.js
- package.json
- yarn.lock
- All Routes calculates all the possible routes in a Questionnaire.
- Updated @datapunt dependencies
> Finished basic question flow with an All Routes option

- app/components/Questionnaire/Answers.js
- app/components/Questionnaire/Content.js
- app/containers/AddressInput/index.js
- app/containers/QuestionnaireContainer/QuestionRoutes.js
- app/containers/QuestionnaireContainer/index.js
- app/shared/content/aanbouw/de-pijp-2018.js
- app/shared/content/aanbouw/rivierenbuurt.js
- app/shared/services/questionnaire/questionnaire.js
- package.json
- yarn.lock
- Added question description ('toelichting') and in Markdown
- WIP: Setting up Registry for monument question
- WIP: Added basic Rivierenbuurt
- disabled Next button on user Input
- enabled all routes
> Question flow based on input

- app/index.html
- added usabilla
- index.html > prettier
> Added usabilla live embed code

- app/components/Questionnaire/Overview.js
- app/components/Questionnaire/Question.js
- app/containers/QuestionnaireContainer/AllQuestions.js
- app/containers/QuestionnaireContainer/index.js
- app/shared/content/aanbouw/de-pijp-2018.js
- Added explanations (short) to AllQuestions debug page
- Added explanations (long) to a new modal placeholder on the Question page
- Added explanations (short) to Overview page
> Added explanations to pages

- app/containers/QuestionnaireContainer/AllQuestions.js
> Minor update on explanations

- app/containers/QuestionnaireContainer/AllQuestions.js
- app/containers/QuestionnaireContainer/index.js
- app/shared/content/aanbouw/de-pijp-2018.js
- Updated position 'Tussenpand' question and removed Output 15
- Added Markdown to AllQuestions debug page
- Updated question explanations from De Pijp
- Removed placeholder texts
> `De pijp` data updates

- app/shared/content/aanbouw/de-pijp-2018.js
> De pijp data updates

- app/containers/HomePage/index.js
Minor update on the HomePage Text
> Updated HomePageText

- app/components/Navigation/index.js
added margin to the prev button in navigation
> added margin to the prev button in navigation

- app/components/Header/index.js
- app/components/LocationData/LocationData.js
- app/components/LocationData/LocationResult.js
- app/constants.js
- app/containers/App/index.js
- app/containers/HomePage/index.js
- app/containers/LocationPage/index.js
- app/containers/QuestionnaireContainer/index.js
- Updated `Header`:
- removed all other `MenuItems` accept for `location`
- added `homeLink` to `amsterdam.nl`
- added `title`
- Updated `LocationPage`:
- added Amsterdam Styled Components
- added specific link to OLO location page
- Updated `constants`:
- added specific OLO links to its intro and location pages
- added `TEXT` and `GET_TEXT`
- added `CURRENT_ACTIVITY`, `CURRENT_PAGE` and `PAGES`
- Updated `App`
- removed `StyledButton` to previous Amsterdam page
- updated `Routes`
> Update LocationPage, Header, App and constants

- app/components/Footer/index.js
- app/components/LocationData/LocationData.js
- app/components/Navigation/index.js
- app/containers/LocationPage/index.js
> LocationPage + Footer styling #101 

- .nginx-acc.conf
- app/.nginx.conf
- app/app.js
- app/containers/App/index.js
- internals/webpack/webpack.prod.babel.js
- package.json
- yarn.lock
- Removed current Service Worker (`OfflinePlugin`)
- Added plugin to remove Service Workers still in current browsers
Hopefully fixes: #92 and #133
> Feature: Removed Service Worker (`OfflinePlugin`) and added `RemoveServiceWorkerPlugin`

- .nginx-acc.conf
- CHANGELOG.md
- app/.nginx.conf
- app/app.js
- app/containers/App/index.js
- internals/webpack/webpack.prod.babel.js
- package.json
- yarn.lock
* Added `RemoveServiceWorkerPlugin` to remove old `OfflinePlugin` 
* Disabled service worker + added dangerous comment
> Release 0.1.4

- CHANGELOG.md
- package.json
> Release 0.1.5 : Tags

- app/containers/Location/CheckerPage.js
- app/containers/Location/IntroductionPage.js
- app/containers/Location/ResultsPage.js
- sttr_build/tests/index.test.js
* Fixed bugs on CheckerPage.js and ResultsPage.js
* Improved styling and text on CheckerPage.js, IntroductionPage.js  and ResultsPage.js
* Refactored ResultsPage.js
* Fixed Lint warning on `sttr_build/tests/index.test.js `
> Location Page improvements: flow, text and bugs

- app/constants.js
- app/containers/Checker/ListInput.js
- app/containers/Checker/QuestionsPage.js
- app/shared/services/sttr_client/models/question.js
* Feat: Do not allow live checkers in Production
* Feat: Added question player based on `sttr-demo`
* Feat: Disabled the question type checker because it breaks the `Aanbouw` checker
> Added question player based on sttr-demo

- app/components/Questionnaire/DebugDecisionTable.js
- app/containers/Checker/QuestionsPage.js
- app/shared/services/sttr_client/models/checker.js
- app/shared/services/sttr_client/models/decision.js
This improves readability on the Debug table but also fixes,
some rewind issues.
> Better implementation for upcoming questions in the checker.

- app/constants.js
- app/containers/Checker/Question.js
- Fix: Typo in dakkapel location Results Page Description
- Fix: IE11 fix with image size
- Fix: Temp disabled the 'dakraam' topic
> Final 0.1 bugs

- apps/client/.gitignore
- apps/client/public/sttr/AanOfUitbouwBouwen.json
- apps/client/public/sttr/DakkapelBouwen.json
- apps/client/public/sttr/GarageOfSchuurBouwen.json
- apps/client/public/sttr/WasstraatOfWasplaatsVoorAutoSBussenTreinenEnTrams.json
- apps/client/public/sttr/topics.json
No need to include xml files, makes our commits much cleaner.
As discussed, we could include a post-install step to generate sttr-files for Developer Experience. With our new approach in committing these files, there is no need anymore. It just works out of the box.
> Added sttr files and gitignore to exclude source.json and .xml files

- apps/client/src/pages/ResultsPage.js
> Implemented feature where only the last decisive input is shown for

- apps/client/src/components/Layouts/BaseLayout.tsx
- apps/client/src/pages/RedirectPage.js
> Update text redirectpage and also improve heading handling by

- app/constants.js
- app/containers/Checker/LocationResultPage.js
- app/containers/Checker/ResultsPage.js
- Feat: added uniqBy to permit results
- Feat: added location Results Page Description 2
> Zonnepaneel updates

- app/components/LocationData/LocationData.js
- app/constants.js
- app/containers/Checker/LocationPage.js
- app/shared/content/sttr/OefenDakkapelPlaatsenOfVeranderen.json
- app/shared/content/sttr/WasstraatOfWasplaatsVoorAutoSBussenTreinenEnTrams.json
- Feat: added matomo trackevent to STTR flow as well
- Feat: Updated maps URLs
- Temp disabled "zonnepanelen"
> Fixed the 0.1 bugs

- apps/client/package-lock.json
- apps/client/package.json
- apps/client/src/components/Nav.js
- apps/client/src/components/Nav.test.js
- apps/graphql/package-lock.json
- apps/graphql/package.json
First  with `Context` and `Router` and Prettier updates
> Chappie1.0 basic FE test + Prettier updates
